const desiredOrder = [
  // SHEETS
  "26ga HHR ROOF SHEETS",
  "26ga Left Wall Sidewall Sheets",
  "26ga Right Wall Sidewall Sheets",
  "26ga HHR ENDWALL PANEL",
  "26ga HHR FRONT GABLE END",
  "26ga HHR REAR GABLE END",
  //   "TRIM",
  "M-29 OUTSIDE CORNER TRIM 5X5",
  "M-29 OUTSIDE GABLE TRIM 5X5",
  "M-15 HEAD / SILL TRIM",
  "M-31 EAVE CLOSURE TRIM",
  "M-30 EAVE CLOSURE TRIM",
  "M-3-BT BASE TRIM - END WALL",
  "M-3-BT BASE TRIM - SIDEWALL",
  "M-33 RIDGE CAP",
  "Front Wall M-29 Trim",
  "Rear Wall M-29 Trim",
  "Left Wall M-29 J Trim",
  "Right Wall M-29 J Trim",
  //   "FRAMING",
  "RUNNER",
  "FRONT RUNNER",
  "REAR RUNNER",
  "LEGS",
  "FRONT LEGS",
  "REAR LEGS",
  "RAFTERS 3:12",
  "R1 PEAK",
  "R2",
  "CORNER BRACES",
  "KNEE BRACE",
  "ROOF BRACE",
  "FRAMING SADDLE FOR RAFTERS",
  "HAT CHANNEL",
  "KINGPIN",
  "ADDITIONAL FRAMING 2.5 x 2.5",
  "COUPLER",
  //"K5 GUTTER SYSTEM",
  "K5 Gutter",
  "K5 Downspout",
  "K5 EndCap",
  "K5 DownspoutStrap",
  "K5 Clip",
  "K5 ElbowA",
  "K5 ElbowB",
  "K5 Gutter Screw",
  "K5 SCUPPER",
  "NovaFlex",
  // "HARDWARE",
  "STRUCTURAL SCREWS",
  "STITCH SCREWS",
  "TEK-3 SCREWS",
  "ANCHOR",
  "OUTSIDE CLOSURE 3' (EA)",
  "ANGLE CLIPS",
  "STRAIGHT CLIPS",
  "TUBECAPS",
  "ButylTape",
];

export default desiredOrder;
