const itemToGroupMap: any = {
  // SHEETS
  "26ga HHR ROOF SHEETS": "SHEETS",
  "26ga Left Wall Sidewall Sheets": "SHEETS",
  "26ga Right Wall Sidewall Sheets": "SHEETS",
  "26ga HHR ENDWALL PANEL": "SHEETS",
  "26ga HHR FRONT GABLE END": "SHEETS",
  "26ga HHR REAR GABLE END": "SHEETS",

  // TRIM
  "M-29 OUTSIDE CORNER TRIM 5X5": "TRIM",
  "M-29 OUTSIDE GABLE TRIM 5X5": "TRIM",
  "M-15 HEAD / SILL TRIM": "TRIM",
  "M-31 EAVE CLOSURE TRIM": "TRIM",
  "M-30 EAVE CLOSURE TRIM": "TRIM",
  "M-3-BT BASE TRIM - END WALL": "TRIM",
  "M-3-BT BASE TRIM - SIDEWALL": "TRIM",
  "M-33 RIDGE CAP": "TRIM",
  "Rear Wall M-29 Trim": "TRIM",
  "Left Wall M-29 J Trim": "TRIM",
  "Right Wall M-29 J Trim": "TRIM",

  // FRAMING
  RUNNER: "FRAMING",
  "FRONT RUNNER": "FRAMING",
  "REAR RUNNER": "FRAMING",
  LEGS: "FRAMING",
  "FRONT LEGS": "FRAMING",
  "REAR LEGS": "FRAMING",
  "RAFTERS 3:12": "FRAMING",
  "R1 PEAK": "FRAMING",
  R2: "FRAMING",
  "CORNER BRACES": "FRAMING",
  "KNEE BRACE": "FRAMING",
  "ROOF BRACE": "FRAMING",
  "FRAMING SADDLE FOR RAFTERS": "FRAMING",
  "HAT CHANNEL": "FRAMING",
  KINGPIN: "FRAMING",
  "ADDITIONAL FRAMING 2.5x2.5": "FRAMING",
  COUPLER: "FRAMING",

  // K5 GUTTER SYSTEM
  "K5 Gutter": "K5 GUTTER SYSTEM",
  "K5 Downspout": "K5 GUTTER SYSTEM",
  "K5 EndCap": "K5 GUTTER SYSTEM",
  "K5 DownspoutStrap": "K5 GUTTER SYSTEM",
  "K5 Clip": "K5 GUTTER SYSTEM",
  "K5 ElbowA": "K5 GUTTER SYSTEM",
  "K5 ElbowB": "K5 GUTTER SYSTEM",
  "K5 Gutter Screw": "K5 GUTTER SYSTEM",
  "K5 SCUPPER": "K5 GUTTER SYSTEM",
  NovaFlex: "K5 GUTTER SYSTEM",

  // HARDWARE
  "STRUCTURAL SCREWS": "HARDWARE",
  "STITCH SCREWS": "HARDWARE",
  "TEK-3 SCREWS": "HARDWARE",
  ANCHOR: "HARDWARE",
  "OUTSIDE CLOSURE 3' (EA)": "HARDWARE",
  "ANGLE CLIPS": "HARDWARE",
  "STRAIGHT CLIPS": "HARDWARE",
  TUBECAPS: "HARDWARE",
  ButylTape: "HARDWARE",
};

export default itemToGroupMap;
